#!/bin/sh

regex='@company\.com'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]];
then
    echo your $email matches to Git policy
    exit 0
else
    echo "your $email doesn't match Git policy"
    exit 1

fi